version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "5173:5173"  # Vite corre en el puerto 5173
    volumes:
      - .:/app  # Monta el código fuente dentro del contenedor para hot-reloading
      - /app/node_modules  # Ignora node_modules para no montarlo en el host
    environment:
      - CHOKIDAR_USEPOLLING=true  # Solución para hot reloading en Docker
