name: Run ascendev actions

on:
 pull_request:
   branches: ["main"]

jobs:
  ascendev:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    name: Check pull requests
    
    steps:
      - name: Check out project
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Run custom action
        uses: tamerlantian01/docker-action-test@v2.0.2
        with:
          base-url: 'https://ascendev-backend-service.onrender.com/api/v1'